server:
  port: 8081
  host: 0.0.0.0
options:
  stripe:
    key: sk_test_xxxXxXxXxXxXxXxXxXxXxXx
    webhook:
      secret: whsec_xxxXxXxXxXxXxXxXxXxXx
  frontend:
    cancel:
      url: https://0x-frontend.xonery.dev/payment/cancel
    success:
      url: https://0x-frontend.xonery.dev/payment/success
  collateral:
    url: https://0x-collateral.xonery.dev
